####################################################################
#                          
#  FILE NAME: Makefile    
#                      
#  DESCRIPTION: This makefile creates the vipercell related class
#               files
#      COMPONENTS:                      
#                              
#                                  
#  NOTES:                              
#                                  
#  (C) Copyright 1999 JetCell Inc., CA, USA http://www.jetcell.com/
#                                 
#  REVISION HISTORY                            
#__________________________________________________________________
#----------+--------+----------------------------------------------
# Name     |  Date  |  Reason                
#----------+--------+----------------------------------------------
# Bhawani  |11/28/99| Initial Draft
#----------+--------+----------------------------------------------
####################################################################
#/

CODEBASE = ../../../../


include $(CODEBASE)/java.mk


all:	$(CLASS_LIST)


clean:
	-$(RM) *.java
	-$(RM) *.class

cleanall:
	-$(RM) *.java
	-$(RM) *.class

