##########################################################
#
#  (c) Copyright Cisco 2000
#  All Rights Reserved
#
##########################################################

SUBDIRS = snmp subsc cc cdc_bsp cdr csunew voip jcc l1proxy lapdm logging mm ril3 rm root socket sslc mch pm alarm http cli cdcUtils TimeSync TcpServer grr rlc_mac bssgp gslink

# TOP_OF_VOB must be defined before including l3defs.mk
TOP_OF_VOB = ..

include $(TOP_OF_VOB)\l3defs.mk
